### ISSUE TITLE
cpu 100%

### ISSUE THREAD

**Issue by GiovannaTes** [consiglionazionaledellericerche/cool-jconon#51]
Salve, dal 24 dicembre quasi a scadenza di un bando l'applicativo ha iniziato a saturare la cpu con il processo "/opt/alfresco-community/java/bin/java -Djava.util.logging.config.file=/opt/alfresco-community/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.jul...", dai log non ci sono particolari evidenze di cosa può causare il problema, solo nei processi si evince una serie di connessioni a postgres come di seguito

postgres  1934  1251  0 11:15 ?        00:00:04 postgres: alfresco alfresco 127.0.0.1(47846) idle
postgres  1935  1251  0 11:15 ?        00:00:03 postgres: alfresco alfresco 127.0.0.1(47848) idle
postgres  1936  1251  0 11:15 ?        00:00:04 postgres: alfresco alfresco 127.0.0.1(47850) idle in transaction
postgres  1937  1251  0 11:15 ?        00:00:01 postgres: alfresco alfresco 127.0.0.1(47852) idle in transaction
postgres  1938  1251  0 11:15 ?        00:00:01 postgres: alfresco alfresco 127.0.0.1(47854) idle in transaction
postgres  1939  1251  0 11:15 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(47856) idle in transaction
postgres  1941  1251  0 11:15 ?        00:00:02 postgres: alfresco alfresco 127.0.0.1(47860) idle in transaction
postgres  1942  1251  0 11:15 ?        00:00:03 postgres: alfresco alfresco 127.0.0.1(47862) idle in transaction

che man mano aumentano fino a bloccare completamente il server portando al cpu in saturazione. 
Potrebbe darci indicazioni su cosa può causare il problema o come procedere per ulteriori analisi.

Saluti
Giovanna

**Comment by mspasiano** [comment]
Salve, che versione di Alfresco e Postgres avete?

**Comment by GiovannaTes** [comment]
per Postgres la versione è 9.2.24, mentre alfresco è la versione 5.2.0

**Comment by mspasiano** [comment]
Putroppo con le sole informazioniche mi hai fornito non riesco a ricreare il problema, potresti provare a modificare il pool di connesioni verso postgres come indicato qui: https://hub.alfresco.com/t5/alfresco-content-services-forum/alfresco-millions-connection-to-postgres/m-p/306707/highlight/true#M24025

**Comment by GiovannaTes** [comment]
ho effettuato la modifica ma la situazione è rimasta invariata. Pultroppo non riesco a darle maggiori informazioni perchè non ho elementi, se le posso inviare qualche file mi dica pure. Questo è quello che vedo nei processi

root     15466     1 99 15:54 ?        00:10:48 /opt/alfresco-community/java/bin/java -Djava.util.logging.config.file=/opt/alfresco-community/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManage
root     15533     2  0 15:54 ?        00:00:00 [kworker/0:0]
postgres 15541  1251  0 15:54 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60016) idle
postgres 15544  1251  0 15:54 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60022) idle
postgres 15545  1251  0 15:54 ?        00:00:01 postgres: alfresco alfresco 127.0.0.1(60024) idle in transaction
postgres 15546  1251  0 15:54 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60026) idle in transaction
postgres 15547  1251  0 15:54 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60028) idle
postgres 15548  1251  0 15:54 ?        00:00:01 postgres: alfresco alfresco 127.0.0.1(60030) idle
postgres 15549  1251  0 15:54 ?        00:00:01 postgres: alfresco alfresco 127.0.0.1(60032) idle
postgres 15564  1251  0 15:55 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60038) idle
root     15587 15466  0 15:55 ?        00:00:00 /opt/alfresco-community/libreoffice/program/.soffice.bin -accept=socket,host=127.0.0.1,port=9100;urp;StarOffice.ServiceManager -env:UserInstallation=file:///opt/alfresco-community/alf_data/
root     15591 15587  0 15:55 ?        00:00:00 [.soffice.bin] <defunct>
postgres 15760  1251  0 15:56 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60060) idle
root     15827     2  0 15:57 ?        00:00:00 [kworker/1:2]
root     15839     1 24 15:58 pts/0    00:00:55 java -jar /root/cool-jconon-template/target/selezioni-template.war --rrd.path=remote-shared,remote-single-model --user.admin.password=2050Svecchiamo!!! --server.servlet.context-path=/ --rep
xymon    15889     1  0 15:58 ?        00:00:00 /bin/sh
xymon    15892 15889  0 15:58 ?        00:00:00 vmstat 300 2
postgres 15971  1251  0 15:59 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60106) idle
postgres 15972  1251  0 15:59 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60108) idle
postgres 16003  1251  0 15:59 ?        00:00:00 postgres: alfresco alfresco 127.0.0.1(60136) idle

e ho appena riavviato il servizio in quanto ho effettuato la modifica

**Comment by mspasiano** [comment]
Guarda il problema potrebbe essere dovuto a SOLR che sta cercando di indicizzare le transazioni jn sospeso, puoi verificare nei log specifici, poi magari puoi fermarlo e riavviare Alfresco senza SOLR e verificare se il problema persiste.

**Comment by GiovannaTes** [comment]
nei log di postgres ho questo errore:
FATAL:  terminating connection due to administrator command

per il log solr invece ho l'errore:
 ERROR [org.alfresco.solr.tracker.AbstractTracker] Tracking failed
org.alfresco.solr.TrackerStateException: 11300006 The trackers work was rolled back by another tracker error
        at org.alfresco.solr.SolrInformationServer.canUpdate(SolrInformationServer.java:3238)
        at org.alfresco.solr.SolrInformationServer.commit(SolrInformationServer.java:773)
        at org.alfresco.solr.tracker.ContentTracker.doTrack(ContentTracker.java:111)
        at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:190)
        at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)

**Comment by mspasiano** [comment]
Ciao, dopo un po di verifiche, credo che la soluzione migliore sia quella di aggiornare le versioni sia di Posgres che di Alfresco, anche perché quelle che mi hai indicato non sono più supportate, per le versioni puoi fare riferimento a quelle presenti qui: https://github.com/consiglionazionaledellericerche/cool-jconon-template/blob/master/docker-compose/docker-compose.yml

**Comment by GiovannaTes** [comment]
Ciao, avendo istallato Alfresco e Jconon senza docker potresti indicarmi la procedura per l'aggiornamento?

**Comment by mspasiano** [comment]
Ciao, potresti seguire questi guida: https://hub.alfresco.com/t5/alfresco-content-services-blog/upgrading-from-alfresco-5-2-installer-to-alfresco-7-0-docker/ba-p/307326
